language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: ApBUqpXH9pdm0ae3jfgUzGTLdEoNIWFnsUrnk1T7004kzcfN544bLiQhMiFDTgjfxFXlXBeoKl2mrmyynKohdAeScX2CWDt+cfFpbKMOnDzUQxJAyKBvtPW8MZVfVxZ8DWQRd1FH5UJY3HMiygDF2XDHB91p0+DbE8QUwpOSX28m7aq9xHK+E1DoFeQx9r21+cohByCjuKbaecz5z8thrJ+nGF9R1TOlwzDekTDLgj7V6jOmbblPo115fcdN9mQlKqQOnsLw0OOcukzmLXe+Ors1ZK6j3WaS1joCCakwGNOtXfs0WIRLtO+xBNaH/4dds5P/AdBSDYWNtQMb1k6ppwzsHnSuJDy1XviS/iwvbsAi7Flc4qkyG6rg9FD57UVzAvS2SgrizpIYtqn3EOHSOpLST2wsSOUw/nQ5ZzzUfPcdX5PCNLZgZdTgeys1WMpvEQhTChK7xt4SnZEp0rrJ2qNDpFqC2nUnFd+KDXlHLHSTCOcvQ1DPg/XlS5M52hOVCzuHEQJQSvsoH7EPv7ZGhBqkN+dgejFkN+GslpvQz2rWmYJo5tbsv80yVPNhmsM0k11K/fKuVyrfukKw0vbcCS29kgwj5q1TLCBQXbAfeAi101dr70htIGpYkcnCXUfWv5Pnocd2tCQAN7DAF8rg16sWGblDYS1xE7e1N4iN96w=
exclude:
- vendor
sudo: false
