version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6-node-browsers-legacy
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4e:9b:48:14:77:b5:38:67:7a:1e:28:ee:bd:22:0d:91"
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'jekyll' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - jekyll