version: 2
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.6-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'jekyll' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy