version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6-node-browsers-legacy
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fc:56:53:6d:93:27:3b:71:87:15:19:de:50:8d:8c:f6"
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'jekyll' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - jekyll